include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - use_build_context_synchronously

analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
    - lib/l10n/**

  strong-mode:
    implicit-casts: false
    implicit-dynamic: true

  errors:
    use_build_context_synchronously: warning
    missing_required_param: warning
    missing_return: warning
    todo: ignore
    deprecated_member_use_from_same_package: ignore
    sdk_version_async_exported_from_core: ignore
    invalid_annotation_target: ignore
    directives_ordering: ignore
    curly_braces_in_flow_control_structures: ignore
