name: sliver_transform
description: Fork of Flutter's Transform widget, that works on slivers
version: 0.0.1
homepage: https://github.com/volskaya/utilities.flutter

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter

flutter:
